### ISSUE TITLE
VersionInfo

### ISSUE THREAD

**Issue by pietru2004** [CRModders/CosmicArchive#17]
Could there be json file that has info does release of CR have client, server or both ?
something like
```json
{
  "releaseid": {
    "tag":"pre-alpha",
    "client":true,
    "server":true
  }
}
```

\+ optionaly field specyfing latest release, althrou it could be fetched from changelog

**Comment by TheEntropyShard** [comment]
That is redundant, just check if client or server key is present in object

**Comment by TheEntropyShard** [comment]
> \+ optionaly field specyfing latest release, althrou it could be fetched from changelog

Wdym? The `versions.json` does have latest key, but currently it is set to latest kinda "stable" version

**Comment by pietru2004** [comment]
@TheEntropyShard  sorry pietru is blind, I forgot about `versions.json`
